info:
    description: Combined Account API specifications
    title: Novofon Account API
    version: 1.0.0
openapi: 3.0.0
paths:
    /get.account:
        get:
            description: "Получение информации об аккаунте\n\n**Request Parameters:** 1\n\n- `access_token` (string, required): Ключ сессии аутентификации\n\n**Response Parameters:** 3\n\n- `app_id` (number): \n\n- `name` (string): \n\n- `timezone` (string): "
            requestBody:
                content:
                    application/json:
                        schema:
                            properties:
                                id:
                                    description: Request identifier
                                    type: number
                                jsonrpc:
                                    description: JSON-RPC version
                                    example: "2.0"
                                    type: string
                                method:
                                    description: Method name
                                    example: get.account
                                    type: string
                                params:
                                    properties:
                                        access_token:
                                            description: Ключ сессии аутентификации
                                            example: example_string
                                            type: string
                                    required:
                                        - access_token
                                    type: object
                            required:
                                - jsonrpc
                                - id
                                - method
                                - params
                            type: object
                required: true
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                properties:
                                    id:
                                        description: Request identifier
                                        type: number
                                    jsonrpc:
                                        description: JSON-RPC version
                                        example: "2.0"
                                        type: string
                                    result:
                                        properties:
                                            data:
                                                properties:
                                                    app_id:
                                                        example: 123
                                                        type: number
                                                    name:
                                                        example: example_string
                                                        type: string
                                                    timezone:
                                                        example: example_string
                                                        type: string
                                                type: object
                                            metadata:
                                                description: Response metadata
                                                type: object
                                        required:
                                            - data
                                            - metadata
                                        type: object
                                required:
                                    - jsonrpc
                                    - id
                                    - result
                                type: object
                    description: Successful response
                "400":
                    content:
                        application/json:
                            schema:
                                properties:
                                    error:
                                        properties:
                                            code:
                                                type: number
                                            data:
                                                type: object
                                            message:
                                                type: string
                                        type: object
                                    id:
                                        type: number
                                    jsonrpc:
                                        type: string
                                type: object
                    description: Error response
            summary: Аккаунт
            tags:
                - novofon
