info:
    description: Combined Authentication Calls API specifications
    title: Novofon Authentication Calls API
    version: 1.0.0
openapi: 3.0.0
paths:
    /login.user:
        post:
            description: |-
                **Request Parameters:** 2

                - `login` (string, required): Логин пользователя

                - `password` (string, required): Пароль пользователя

                **Response Parameters:** 2

                - `access_token` (string): Ключ сессии аутентификации

                - `expire_at` (number): Timestamp когда выданный токен перестанет быть валидным
            requestBody:
                content:
                    application/json:
                        schema:
                            properties:
                                id:
                                    description: Request identifier
                                    type: number
                                jsonrpc:
                                    description: JSON-RPC version
                                    example: "2.0"
                                    type: string
                                method:
                                    description: Method name
                                    example: login.user
                                    type: string
                                params:
                                    properties:
                                        login:
                                            description: Логин пользователя
                                            example: example_string
                                            type: string
                                        password:
                                            description: Пароль пользователя
                                            example: example_string
                                            type: string
                                    required:
                                        - login
                                        - password
                                    type: object
                            required:
                                - jsonrpc
                                - id
                                - method
                                - params
                            type: object
                required: true
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                properties:
                                    id:
                                        description: Request identifier
                                        type: number
                                    jsonrpc:
                                        description: JSON-RPC version
                                        example: "2.0"
                                        type: string
                                    result:
                                        properties:
                                            data:
                                                properties:
                                                    access_token:
                                                        description: Ключ сессии аутентификации
                                                        example: example_string
                                                        type: string
                                                    expire_at:
                                                        description: Timestamp когда выданный токен перестанет быть валидным
                                                        example: 123
                                                        type: number
                                                required:
                                                    - access_token
                                                    - expire_at
                                                type: object
                                            metadata:
                                                description: Response metadata
                                                type: object
                                        required:
                                            - data
                                            - metadata
                                        type: object
                                required:
                                    - jsonrpc
                                    - id
                                    - result
                                type: object
                    description: Successful response
                "400":
                    content:
                        application/json:
                            schema:
                                properties:
                                    error:
                                        properties:
                                            code:
                                                type: number
                                            data:
                                                type: object
                                            message:
                                                type: string
                                        type: object
                                    id:
                                        type: number
                                    jsonrpc:
                                        type: string
                                type: object
                    description: Error response
            summary: Login user
            tags:
                - novofon
    /logout.user:
        post:
            description: |-
                **Request Parameters:** 1

                - `access_token` (string, required): Ключ сессии аутентификации
            requestBody:
                content:
                    application/json:
                        schema:
                            properties:
                                id:
                                    description: Request identifier
                                    type: number
                                jsonrpc:
                                    description: JSON-RPC version
                                    example: "2.0"
                                    type: string
                                method:
                                    description: Method name
                                    example: logout.user
                                    type: string
                                params:
                                    properties:
                                        access_token:
                                            description: Ключ сессии аутентификации
                                            example: example_string
                                            type: string
                                    required:
                                        - access_token
                                    type: object
                            required:
                                - jsonrpc
                                - id
                                - method
                                - params
                            type: object
                required: true
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                properties:
                                    id:
                                        description: Request identifier
                                        type: number
                                    jsonrpc:
                                        description: JSON-RPC version
                                        example: "2.0"
                                        type: string
                                    result:
                                        properties:
                                            data:
                                                type: object
                                            metadata:
                                                description: Response metadata
                                                type: object
                                        required:
                                            - data
                                            - metadata
                                        type: object
                                required:
                                    - jsonrpc
                                    - id
                                    - result
                                type: object
                    description: Successful response
                "400":
                    content:
                        application/json:
                            schema:
                                properties:
                                    error:
                                        properties:
                                            code:
                                                type: number
                                            data:
                                                type: object
                                            message:
                                                type: string
                                        type: object
                                    id:
                                        type: number
                                    jsonrpc:
                                        type: string
                                type: object
                    description: Error response
            summary: Logout user
            tags:
                - novofon
