info:
    description: Combined Scenario API specifications
    title: Novofon Scenario API
    version: 1.0.0
openapi: 3.0.0
paths:
    /get.scenarios:
        get:
            description: |-
                Получение списка сценариев

                **Request Parameters:** 7

                - `fields` (array, optional): См. раздел Представление возвращаемых данных

                - `sort` (array, optional): См. раздел Сортировка данных

                - `access_token` (string, required): Ключ сессии аутентификации

                - `user_id` (number, optional): Уникальный идентификатор пользователя клиента агента от имени которого делается запрос Является обязательным для агента Для получения списка пользователей клиента необходимо использовать метод "get.customer_users"

                - `limit` (number, optional): Количество возвращаемых записей. См. раздел Постраничный вывод

                - `offset` (number, optional): Сдвиг, определяет с какого номера записи возвращать limit записей. По умолчанию 0. См. раздел Постраничный вывод

                - `filter` (object, optional): См. раздел Критерии фильтрации

                **Response Parameters:** 6

                - `campaigns` (array): Да

                - `operations` (array): Да

                - `id` (number): Да

                - `name` (string): Да

                - `virtual_phone_numbers` (array): Да

                - `sites` (array): Да
            requestBody:
                content:
                    application/json:
                        schema:
                            properties:
                                id:
                                    description: Request identifier
                                    type: number
                                jsonrpc:
                                    description: JSON-RPC version
                                    example: "2.0"
                                    type: string
                                method:
                                    description: Method name
                                    example: get.scenarios
                                    type: string
                                params:
                                    properties:
                                        access_token:
                                            description: Ключ сессии аутентификации
                                            example: example_string
                                            type: string
                                        fields:
                                            description: См. раздел Представление возвращаемых данных
                                            example: []
                                            items:
                                                example: example_string
                                                type: string
                                            type: array
                                        filter:
                                            description: См. раздел Критерии фильтрации
                                            type: object
                                        limit:
                                            description: Количество возвращаемых записей. См. раздел Постраничный вывод
                                            example: 123
                                            type: number
                                        offset:
                                            description: Сдвиг, определяет с какого номера записи возвращать limit записей. По умолчанию 0. См. раздел Постраничный вывод
                                            example: 123
                                            type: number
                                        sort:
                                            description: См. раздел Сортировка данных
                                            example: []
                                            items:
                                                example: example_string
                                                type: string
                                            type: array
                                        user_id:
                                            description: Уникальный идентификатор пользователя клиента агента от имени которого делается запрос Является обязательным для агента Для получения списка пользователей клиента необходимо использовать метод "get.customer_users"
                                            example: 123
                                            type: number
                                    required:
                                        - access_token
                                    type: object
                            required:
                                - jsonrpc
                                - id
                                - method
                                - params
                            type: object
                required: true
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                properties:
                                    id:
                                        description: Request identifier
                                        type: number
                                    jsonrpc:
                                        description: JSON-RPC version
                                        example: "2.0"
                                        type: string
                                    result:
                                        properties:
                                            data:
                                                properties:
                                                    campaigns:
                                                        description: Да
                                                        example: []
                                                        items:
                                                            example: example_string
                                                            type: string
                                                        type: array
                                                    id:
                                                        description: Да
                                                        example: 123
                                                        type: number
                                                    name:
                                                        description: Да
                                                        example: example_string
                                                        type: string
                                                    operations:
                                                        description: Да
                                                        example: []
                                                        items:
                                                            example: example_string
                                                            type: string
                                                        type: array
                                                    sites:
                                                        description: Да
                                                        example: []
                                                        items:
                                                            example: example_string
                                                            type: string
                                                        type: array
                                                    virtual_phone_numbers:
                                                        description: Да
                                                        example: []
                                                        items:
                                                            example: example_string
                                                            type: string
                                                        type: array
                                                type: object
                                            metadata:
                                                description: Response metadata
                                                type: object
                                        required:
                                            - data
                                            - metadata
                                        type: object
                                required:
                                    - jsonrpc
                                    - id
                                    - result
                                type: object
                    description: Successful response
                "400":
                    content:
                        application/json:
                            schema:
                                properties:
                                    error:
                                        properties:
                                            code:
                                                type: number
                                            data:
                                                type: object
                                            message:
                                                type: string
                                        type: object
                                    id:
                                        type: number
                                    jsonrpc:
                                        type: string
                                type: object
                    description: Error response
            summary: Сценарии
            tags:
                - novofon
