info:
    description: Combined User_media API specifications
    title: Novofon User_media API
    version: 1.0.0
openapi: 3.0.0
paths:
    /get.media_files:
        get:
            description: "Получение списка медиафайлов\n\n**Request Parameters:** 7\n\n- `sort` (array, optional): См. раздел Сортировка данных\n\n- `access_token` (string, required): Ключ сессии аутентификации\n\n- `user_id` (number, optional): Уникальный идентификатор пользователя клиента агента от имени которого делается запрос Является обязательным для агента Для получения списка пользователей клиента необходимо использовать метод \"get.customer_users\"\n\n- `limit` (number, optional): Количество возвращаемых записей. См. раздел Постраничный вывод\n\n- `offset` (number, optional): Сдвиг, определяет с какого номера записи возвращать limit записей. По умолчанию 0. См. раздел Постраничный вывод\n\n- `filter` (object, optional): См. раздел Критерии фильтрации\n\n- `fields` (array, optional): См. раздел Представление возвращаемых данных\n\n**Response Parameters:** 7\n\n- `id` (number): Да\n\n- `name` (string): Да\n\n- `duration` (number): Да\n\n- `play_link` (string): \n\n- `normalization` (boolean): Да\n\n- `size` (number): Да\n\n- `type` (enum): Да"
            requestBody:
                content:
                    application/json:
                        schema:
                            properties:
                                id:
                                    description: Request identifier
                                    type: number
                                jsonrpc:
                                    description: JSON-RPC version
                                    example: "2.0"
                                    type: string
                                method:
                                    description: Method name
                                    example: get.media_files
                                    type: string
                                params:
                                    properties:
                                        access_token:
                                            description: Ключ сессии аутентификации
                                            example: example_string
                                            type: string
                                        fields:
                                            description: См. раздел Представление возвращаемых данных
                                            example: []
                                            items:
                                                example: example_string
                                                type: string
                                            type: array
                                        filter:
                                            description: См. раздел Критерии фильтрации
                                            type: object
                                        limit:
                                            description: Количество возвращаемых записей. См. раздел Постраничный вывод
                                            example: 123
                                            type: number
                                        offset:
                                            description: Сдвиг, определяет с какого номера записи возвращать limit записей. По умолчанию 0. См. раздел Постраничный вывод
                                            example: 123
                                            type: number
                                        sort:
                                            description: См. раздел Сортировка данных
                                            example: []
                                            items:
                                                example: example_string
                                                type: string
                                            type: array
                                        user_id:
                                            description: Уникальный идентификатор пользователя клиента агента от имени которого делается запрос Является обязательным для агента Для получения списка пользователей клиента необходимо использовать метод "get.customer_users"
                                            example: 123
                                            type: number
                                    required:
                                        - access_token
                                    type: object
                            required:
                                - jsonrpc
                                - id
                                - method
                                - params
                            type: object
                required: true
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                properties:
                                    id:
                                        description: Request identifier
                                        type: number
                                    jsonrpc:
                                        description: JSON-RPC version
                                        example: "2.0"
                                        type: string
                                    result:
                                        properties:
                                            data:
                                                properties:
                                                    duration:
                                                        description: Да
                                                        example: 123
                                                        type: number
                                                    id:
                                                        description: Да
                                                        example: 123
                                                        type: number
                                                    name:
                                                        description: Да
                                                        example: example_string
                                                        type: string
                                                    normalization:
                                                        description: Да
                                                        example: true
                                                        type: boolean
                                                    play_link:
                                                        example: example_string
                                                        type: string
                                                    size:
                                                        description: Да
                                                        example: 123
                                                        type: number
                                                    type:
                                                        description: Да
                                                        type: string
                                                type: object
                                            metadata:
                                                description: Response metadata
                                                type: object
                                        required:
                                            - data
                                            - metadata
                                        type: object
                                required:
                                    - jsonrpc
                                    - id
                                    - result
                                type: object
                    description: Successful response
                "400":
                    content:
                        application/json:
                            schema:
                                properties:
                                    error:
                                        properties:
                                            code:
                                                type: number
                                            data:
                                                type: object
                                            message:
                                                type: string
                                        type: object
                                    id:
                                        type: number
                                    jsonrpc:
                                        type: string
                                type: object
                    description: Error response
            summary: Медиафайлы
            tags:
                - novofon
