openapi: 3.0.0
info:
  title: Call talk option
  version: 1.0.0
  description: Call talk option
paths:
  /call.talk_option:
    post:
      summary: Call talk option
      description: Call talk option
      requestBody:
        required: false
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  jsonrpc:
                    type: string
                    example: '2.0'
                    description: JSON-RPC version
                  id:
                    type: number
                    description: Request identifier
                  result:
                    type: object
                    properties:
                      data:
                        type: object
                      metadata:
                        type: object
                        description: Response metadata
                    required:
                    - data
                    - metadata
                required:
                - jsonrpc
                - id
                - result
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  jsonrpc:
                    type: string
                  id:
                    type: number
                  error:
                    type: object
                    properties:
                      code:
                        type: number
                      message:
                        type: string
                      data:
                        type: object
        This method can not be called in this state:
          description: '-32004'
          content:
            application/json:
              schema:
                type: object
                properties:
                  jsonrpc:
                    type: string
                  id:
                    type: number
                  error:
                    type: object
                    properties:
                      code:
                        type: number
                        example: null
                      message:
                        type: string
                        example: '-32004'
                      data:
                        type: object
        Internal error, contact the support service:
          description: '-32603'
          content:
            application/json:
              schema:
                type: object
                properties:
                  jsonrpc:
                    type: string
                  id:
                    type: number
                  error:
                    type: object
                    properties:
                      code:
                        type: number
                        example: null
                      message:
                        type: string
                        example: '-32603'
                      data:
                        type: object
        Permission denied:
          description: '-32003'
          content:
            application/json:
              schema:
                type: object
                properties:
                  jsonrpc:
                    type: string
                  id:
                    type: number
                  error:
                    type: object
                    properties:
                      code:
                        type: number
                        example: null
                      message:
                        type: string
                        example: '-32003'
                      data:
                        type: object
        Call session not found:
          description: '-32602'
          content:
            application/json:
              schema:
                type: object
                properties:
                  jsonrpc:
                    type: string
                  id:
                    type: number
                  error:
                    type: object
                    properties:
                      code:
                        type: number
                        example: null
                      message:
                        type: string
                        example: '-32602'
                      data:
                        type: object
        Talk option not found:
          description: '-32602'
          content:
            application/json:
              schema:
                type: object
                properties:
                  jsonrpc:
                    type: string
                  id:
                    type: number
                  error:
                    type: object
                    properties:
                      code:
                        type: number
                        example: null
                      message:
                        type: string
                        example: '-32602'
                      data:
                        type: object
x-errors:
  errors:
  - code: This method can not be called in this state
    description: '-32004'
  - code: Internal error, contact the support service
    description: '-32603'
  - code: Permission denied
    description: '-32003'
  - code: Call session not found
    description: '-32602'
  - code: Talk option not found
    description: '-32602'
  error_references: []
