openapi: 3.0.0
info:
  title: Start simple call
  version: 1.0.0
  description: Start simple call
paths:
  /start.simple_call:
    post:
      summary: Start simple call
      description: Start simple call
      requestBody:
        required: false
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  jsonrpc:
                    type: string
                    example: '2.0'
                    description: JSON-RPC version
                  id:
                    type: number
                    description: Request identifier
                  result:
                    type: object
                    properties:
                      data:
                        type: object
                      metadata:
                        type: object
                        description: Response metadata
                    required:
                    - data
                    - metadata
                required:
                - jsonrpc
                - id
                - result
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  jsonrpc:
                    type: string
                  id:
                    type: number
                  error:
                    type: object
                    properties:
                      code:
                        type: number
                      message:
                        type: string
                      data:
                        type: object
        ? The maximum length of Text-to-Speech message is {tts_message_max_length}.
          The length of your message is {sent_tts_message_length}
        : description: '-32602'
          content:
            application/json:
              schema:
                type: object
                properties:
                  jsonrpc:
                    type: string
                  id:
                    type: number
                  error:
                    type: object
                    properties:
                      code:
                        type: number
                        example: null
                      message:
                        type: string
                        example: '-32602'
                      data:
                        type: object
        The media file with id {media_file_id} not found:
          description: '-32602'
          content:
            application/json:
              schema:
                type: object
                properties:
                  jsonrpc:
                    type: string
                  id:
                    type: number
                  error:
                    type: object
                    properties:
                      code:
                        type: number
                        example: null
                      message:
                        type: string
                        example: '-32602'
                      data:
                        type: object
        Virtual phone number {virtual_phone_number} not found. It is not your virtual phone number.:
          description: '-32007'
          content:
            application/json:
              schema:
                type: object
                properties:
                  jsonrpc:
                    type: string
                  id:
                    type: number
                  error:
                    type: object
                    properties:
                      code:
                        type: number
                        example: null
                      message:
                        type: string
                        example: '-32007'
                      data:
                        type: object
        Parameter contact can not contain own virtual phone number:
          description: '-32602'
          content:
            application/json:
              schema:
                type: object
                properties:
                  jsonrpc:
                    type: string
                  id:
                    type: number
                  error:
                    type: object
                    properties:
                      code:
                        type: number
                        example: null
                      message:
                        type: string
                        example: '-32602'
                      data:
                        type: object
        The contact {contact} has been found in the blacklist:
          description: '-32002'
          content:
            application/json:
              schema:
                type: object
                properties:
                  jsonrpc:
                    type: string
                  id:
                    type: number
                  error:
                    type: object
                    properties:
                      code:
                        type: number
                        example: null
                      message:
                        type: string
                        example: '-32002'
                      data:
                        type: object
        The character encoding must be UTF-8:
          description: '-32602'
          content:
            application/json:
              schema:
                type: object
                properties:
                  jsonrpc:
                    type: string
                  id:
                    type: number
                  error:
                    type: object
                    properties:
                      code:
                        type: number
                        example: null
                      message:
                        type: string
                        example: '-32602'
                      data:
                        type: object
x-errors:
  errors:
  - code: The maximum length of Text-to-Speech message is {tts_message_max_length}.
      The length of your message is {sent_tts_message_length}
    description: '-32602'
  - code: The media file with id {media_file_id} not found
    description: '-32602'
  - code: Virtual phone number {virtual_phone_number} not found. It is not your virtual
      phone number.
    description: '-32007'
  - code: Parameter contact can not contain own virtual phone number
    description: '-32602'
  - code: The contact {contact} has been found in the blacklist
    description: '-32002'
  - code: The character encoding must be UTF-8
    description: '-32602'
  error_references: []
