openapi: 3.0.0
info:
    title: Record call
    version: 1.0.0
    description: Управление записью разговора. Отключить запись разговора, настроенную через личный кабинет невозможно.
paths:
    /record.call:
        post:
            summary: Record call
            description: |-
                Управление записью разговора. Отключить запись разговора, настроенную через личный кабинет невозможно.

                **Request Parameters:** 3

                - `action` (string, required): Действие над записью разговора. on - включение записи разговора, off - выключение записи разговора

                - `access_token` (string, required): Ключ сессии аутентификации

                - `call_session_id` (number, required): Уникальный идентификатор сессии звонка, который может быть получен в ответном сообщении при вызове методов start.informer_call, start.vnumber_call, start.scenario_call, start.employee_call, с помощью сервера уведомлений или DATA API.
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                id:
                                    type: number
                                    description: Request identifier
                                jsonrpc:
                                    type: string
                                    description: JSON-RPC version
                                    example: "2.0"
                                method:
                                    type: string
                                    description: Method name
                                    example: record.call
                                params:
                                    type: object
                                    properties:
                                        access_token:
                                            type: string
                                            description: Ключ сессии аутентификации
                                            example: example_string
                                        action:
                                            type: string
                                            description: Действие над записью разговора. on - включение записи разговора, off - выключение записи разговора
                                            example: "on"
                                            enum:
                                                - "on"
                                                - "off"
                                        call_session_id:
                                            type: number
                                            description: Уникальный идентификатор сессии звонка, который может быть получен в ответном сообщении при вызове методов start.informer_call, start.vnumber_call, start.scenario_call, start.employee_call, с помощью сервера уведомлений или DATA API.
                                            example: 123
                                    required:
                                        - access_token
                                        - call_session_id
                                        - action
                            required:
                                - jsonrpc
                                - id
                                - method
                                - params
            responses:
                "200":
                    description: Successful response
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    id:
                                        type: number
                                        description: Request identifier
                                    jsonrpc:
                                        type: string
                                        description: JSON-RPC version
                                        example: "2.0"
                                    result:
                                        type: object
                                        properties:
                                            data:
                                                type: object
                                            metadata:
                                                type: object
                                                description: Response metadata
                                        required:
                                            - data
                                            - metadata
                                required:
                                    - jsonrpc
                                    - id
                                    - result
                "400":
                    description: Error response
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    error:
                                        type: object
                                        properties:
                                            code:
                                                type: number
                                            data:
                                                type: object
                                            message:
                                                type: string
                                    id:
                                        type: number
                                    jsonrpc:
                                        type: string
            tags:
                - novofon
x-errors:
    errors:
        - code: "-32003"
          mnemonic: forbidden
          description: Невозможно отключить глобальную запись разговора. Глобальной записью разговора является настройка на уровне настройки сотрудника.
        - code: "-32602"
          mnemonic: record_already_started
          description: Запись разговора уже включена
        - code: "-32602"
          mnemonic: record_already_stopped
          description: Запись разговора не была включена
