openapi: 3.0.0
info:
    title: Hold call
    version: 1.0.0
    description: Постановка вызова на удержание
paths:
    /hold.call:
        post:
            summary: Hold call
            description: |-
                Постановка вызова на удержание

                **Request Parameters:** 3

                - `contact_message` (object, required): Определяет параметры сообщения, которое необходимо проиграть вызывающему абоненту. Вызывающий абонент - это номер, указанный в параметре contact в методах start.informer_call, start.vnumber_call, start.scenario_call, start.employee_call или абонент позвонивший на виртуальную АТС.

                - `access_token` (string, required): Ключ сессии аутентификации

                - `call_session_id` (number, required): Уникальный идентификатор сессии звонка, который может быть получен в ответном сообщении при вызове методов start.vnumber_call, start.scenario_call, start.employee_call, с помощью сервера уведомлений или DATA API.
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                id:
                                    type: number
                                    description: Request identifier
                                jsonrpc:
                                    type: string
                                    description: JSON-RPC version
                                    example: "2.0"
                                method:
                                    type: string
                                    description: Method name
                                    example: hold.call
                                params:
                                    type: object
                                    properties:
                                        access_token:
                                            type: string
                                            description: Ключ сессии аутентификации
                                            example: example_string
                                        call_session_id:
                                            type: number
                                            description: Уникальный идентификатор сессии звонка, который может быть получен в ответном сообщении при вызове методов start.vnumber_call, start.scenario_call, start.employee_call, с помощью сервера уведомлений или DATA API.
                                            example: 123
                                        contact_message:
                                            type: object
                                            description: Определяет параметры сообщения, которое необходимо проиграть вызывающему абоненту. Вызывающий абонент - это номер, указанный в параметре contact в методах start.informer_call, start.vnumber_call, start.scenario_call, start.employee_call или абонент позвонивший на виртуальную АТС.
                                    required:
                                        - call_session_id
                                        - contact_message
                                        - access_token
                            required:
                                - jsonrpc
                                - id
                                - method
                                - params
            responses:
                "200":
                    description: Successful response
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    id:
                                        type: number
                                        description: Request identifier
                                    jsonrpc:
                                        type: string
                                        description: JSON-RPC version
                                        example: "2.0"
                                    result:
                                        type: object
                                        properties:
                                            data:
                                                type: object
                                            metadata:
                                                type: object
                                                description: Response metadata
                                        required:
                                            - data
                                            - metadata
                                required:
                                    - jsonrpc
                                    - id
                                    - result
                "400":
                    description: Error response
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    error:
                                        type: object
                                        properties:
                                            code:
                                                type: number
                                            data:
                                                type: object
                                            message:
                                                type: string
                                    id:
                                        type: number
                                    jsonrpc:
                                        type: string
            tags:
                - novofon
x-errors:
    errors:
        - code: "-32004"
          mnemonic: invalid_state
          description: Метод может быть вызван только в состоянии Talk (см. Диаграмма состояний звонка)
        - code: "-32602"
          mnemonic: media_file_not_found
          description: ""
        - code: "-32602"
          mnemonic: tts_text_exceeded
          description: Длина сообщения превысила допустимое ограничение, установленное тарифным планом
        - code: "-32602"
          mnemonic: character_encoding_not_allowed
          description: ""
