openapi: 3.0.0
info:
    title: Make call
    version: 1.0.0
    description: Создать звонок для трансфера или консультации
paths:
    /make.call:
        post:
            summary: Make call
            description: |-
                Создать звонок для трансфера или консультации

                **Request Parameters:** 4

                - `to_message` (object, optional): Определяет параметры сообщения, которое необходимо проиграть абоненту заданному в параметре to_message. Абонент, который стоит на удержании, будет ожидать ответа, пока не будет прослушано сообщение до конца

                - `access_token` (string, required): Ключ сессии аутентификации

                - `call_session_id` (number, required): Уникальный идентификатор сессии звонка, который может быть получен в ответном сообщении при вызове методов start.informer_call, start.vnumber_call, start.scenario_call, start.employee_call, с помощью сервера уведомлений или DATA API.

                - `to` (string, required): Номер абонента на который совершаем звонок. Формат номера должен соответствовать международному стандарту E.164 Может быть внутренний номер, внешний номер, номер сотрудника, sip-номер
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                id:
                                    type: number
                                    description: Request identifier
                                jsonrpc:
                                    type: string
                                    description: JSON-RPC version
                                    example: "2.0"
                                method:
                                    type: string
                                    description: Method name
                                    example: make.call
                                params:
                                    type: object
                                    properties:
                                        access_token:
                                            type: string
                                            description: Ключ сессии аутентификации
                                            example: example_string
                                        call_session_id:
                                            type: number
                                            description: Уникальный идентификатор сессии звонка, который может быть получен в ответном сообщении при вызове методов start.informer_call, start.vnumber_call, start.scenario_call, start.employee_call, с помощью сервера уведомлений или DATA API.
                                            example: 123
                                        to:
                                            type: string
                                            description: Номер абонента на который совершаем звонок. Формат номера должен соответствовать международному стандарту E.164 Может быть внутренний номер, внешний номер, номер сотрудника, sip-номер
                                            example: example_string
                                        to_message:
                                            type: object
                                            description: Определяет параметры сообщения, которое необходимо проиграть абоненту заданному в параметре to_message. Абонент, который стоит на удержании, будет ожидать ответа, пока не будет прослушано сообщение до конца
                                    required:
                                        - access_token
                                        - call_session_id
                                        - to
                            required:
                                - jsonrpc
                                - id
                                - method
                                - params
            responses:
                "200":
                    description: Successful response
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    id:
                                        type: number
                                        description: Request identifier
                                    jsonrpc:
                                        type: string
                                        description: JSON-RPC version
                                        example: "2.0"
                                    result:
                                        type: object
                                        properties:
                                            data:
                                                type: object
                                            metadata:
                                                type: object
                                                description: Response metadata
                                        required:
                                            - data
                                            - metadata
                                required:
                                    - jsonrpc
                                    - id
                                    - result
                "400":
                    description: Error response
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    error:
                                        type: object
                                        properties:
                                            code:
                                                type: number
                                            data:
                                                type: object
                                            message:
                                                type: string
                                    id:
                                        type: number
                                    jsonrpc:
                                        type: string
            tags:
                - novofon
x-errors:
    errors:
        - code: "-32004"
          mnemonic: invalid_state
          description: Метод может быть вызван только после метода hold.call
        - code: "-32602"
          mnemonic: character_encoding_not_allowed
          description: ""
        - code: "-32602"
          mnemonic: no_active_phone_number
          description: У сотрудника могут отсутствовать активные номера
