openapi: 3.0.0
info:
    title: List calls
    version: 1.0.0
    description: Получить список активных вызовов и их участников
paths:
    /list.calls:
        post:
            summary: List calls
            description: "Получить список активных вызовов и их участников\n\n**Request Parameters:** 3\n\n- `access_token` (string, required): Ключ сессии аутентификации\n\n- `direction` (string, optional): Указывает какие сессии выводить - входящие, исходящие. Если параметр не задан, то выводятся все сессии.\n\n- `virtual_phone_number` (string, optional): Указывает с каким виртуальным номер активные вызовы показывать. Номер должен начинаться с 7\n\n**Response Parameters:** 8\n\n- `external_id` (string): \n\n- `tags` (array): \n\n- `legs` (array): \n\n- `call_session_id` (number): \n\n- `direction` (string): in, out\n\n- `start_time` (string): \n\n- `virtual_phone_number` (string): \n\n- `contact_phone_number` (string): "
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                id:
                                    type: number
                                    description: Request identifier
                                jsonrpc:
                                    type: string
                                    description: JSON-RPC version
                                    example: "2.0"
                                method:
                                    type: string
                                    description: Method name
                                    example: list.calls
                                params:
                                    type: object
                                    properties:
                                        access_token:
                                            type: string
                                            description: Ключ сессии аутентификации
                                            example: example_string
                                        direction:
                                            type: string
                                            description: Указывает какие сессии выводить - входящие, исходящие. Если параметр не задан, то выводятся все сессии.
                                            example: in
                                            enum:
                                                - in
                                                - out
                                        virtual_phone_number:
                                            type: string
                                            description: Указывает с каким виртуальным номер активные вызовы показывать. Номер должен начинаться с 7
                                            example: example_string
                                    required:
                                        - access_token
                            required:
                                - jsonrpc
                                - id
                                - method
                                - params
            responses:
                "200":
                    description: Successful response
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    id:
                                        type: number
                                        description: Request identifier
                                    jsonrpc:
                                        type: string
                                        description: JSON-RPC version
                                        example: "2.0"
                                    result:
                                        type: object
                                        properties:
                                            data:
                                                type: object
                                                properties:
                                                    call_session_id:
                                                        type: number
                                                        example: 123
                                                    contact_phone_number:
                                                        type: string
                                                        example: example_string
                                                    direction:
                                                        type: string
                                                        description: in, out
                                                        example: example_string
                                                    external_id:
                                                        type: string
                                                        example: example_string
                                                    legs:
                                                        type: array
                                                        example: []
                                                        items:
                                                            type: string
                                                            example: example_string
                                                    start_time:
                                                        type: string
                                                        example: example_string
                                                    tags:
                                                        type: array
                                                        example: []
                                                        items:
                                                            type: string
                                                            example: example_string
                                                    virtual_phone_number:
                                                        type: string
                                                        example: example_string
                                                required:
                                                    - virtual_phone_number
                                                    - contact_phone_number
                                                    - external_id
                                                    - tags
                                                    - legs
                                                    - call_session_id
                                                    - direction
                                                    - start_time
                                            metadata:
                                                type: object
                                                description: Response metadata
                                        required:
                                            - data
                                            - metadata
                                required:
                                    - jsonrpc
                                    - id
                                    - result
                "400":
                    description: Error response
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    error:
                                        type: object
                                        properties:
                                            code:
                                                type: number
                                            data:
                                                type: object
                                            message:
                                                type: string
                                    id:
                                        type: number
                                    jsonrpc:
                                        type: string
            tags:
                - novofon
