openapi: 3.0.0
info:
    title: Start informer call
    version: 1.0.0
    description: Информационный вызов с возможностью проиграть абоненту файл или текстовое сообщение. После окончания проигрывания сообщения вызов завершается автоматически.
paths:
    /start.informer_call:
        post:
            summary: Start informer call
            description: "Информационный вызов с возможностью проиграть абоненту файл или текстовое сообщение. После окончания проигрывания сообщения вызов завершается автоматически.\n\n**Request Parameters:** 9\n\n- `access_token` (string, required): Ключ сессии аутентификации\n\n- `virtual_phone_number` (string, required): Виртуальный номер, арендуемый клиентом. Формат номера должен соответствовать международному\n                    стандарту E.164 (например, 74993720692). Всегда используется в качестве номера звонящего при звонке\n                    на номер, указанный в параметре contact. Виртуальные номера можно получить с помощью REST\n                    API метода - Получение списка виртуальных номеров\n\n- `virtual_phone_usage_rule` (string, optional): Правило использования виртуального номера. Позволяет динамически менять виртуальный номер при звонке. Если подходящий номер,\n                    удовлетворяющий выбранному правилу, не найден, то будет использован номер, указанный в параметре virtual_phone_number.\n                    Допустимые значения параметра:\n                \n                \n                    fixed - Фиксированный\n                    fixed_for_numa - Фиксированный для абонента\n                    random - Случайный\n                    regional_random - Региональный случайный\n                    regional_fixed_for_numa - Региональный фиксированный для абонента\n                \n                \n                    По умолчанию используется правило Фиксированный. Остальные правила доступны при подключённом компоненте\n                    Автоматическое управление номерами.\n\n- `dtmf_string` (string, optional): Задаёт DTMF, который будет отправлен абоненту, заданному в параметре contact. С\n                помощью символа . = '1 секунда' можно задать таймаут по истечению которого символ DTMF будет отправлен. Пример: .12.1..4, т.е через 1 секунду\n                будет отправлена цифра 12, далее через 1 секунду будет отправлена цифра 1 и через 2 секунды цифра 4.\n\n- `contact` (string, required): Номер абонента на который совершается вызов. Формат номера должен соответствовать\n                    международному стандарту E.164 (например, 79091234567). В качестве номера может быть так же указан SIP номер сотрудника.\n                \n                Внутренние номера сотрудников не поддерживаются.\n\n- `dialing_timeout` (number, optional): Значение по умолчанию 30. Время ожидания ответа от номера, заданного в параметре contact,\n                если ответ не был получен, то вызов завершается. Время задаётся в секундах.\n\n- `contact_message` (object, required): Определяет параметры сообщения, которое необходимо проиграть абоненту заданному в параметре contact.\n\n- `external_id` (string, optional): Уникальный идентификатор, который может быть использован для связи события звонка с внешней системой.\n\n- `direction` (string, optional): Значение по умолчанию in. \n                Определяет направление звонка in - Входящий звонок, out - Исходящий звонок.\n\n**Response Parameters:** 1\n\n- `call_session_id` (number): Уникальный идентификатор сессии звонка"
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                id:
                                    type: number
                                    description: Request identifier
                                jsonrpc:
                                    type: string
                                    description: JSON-RPC version
                                    example: "2.0"
                                method:
                                    type: string
                                    description: Method name
                                    example: start.informer_call
                                params:
                                    type: object
                                    properties:
                                        access_token:
                                            type: string
                                            description: Ключ сессии аутентификации
                                            example: example_string
                                        contact:
                                            type: string
                                            description: "Номер абонента на который совершается вызов. Формат номера должен соответствовать\n                    международному стандарту E.164 (например, 79091234567). В качестве номера может быть так же указан SIP номер сотрудника.\n                \n                Внутренние номера сотрудников не поддерживаются."
                                            example: example_string
                                        contact_message:
                                            type: object
                                            description: Определяет параметры сообщения, которое необходимо проиграть абоненту заданному в параметре contact.
                                        dialing_timeout:
                                            type: number
                                            description: |-
                                                Значение по умолчанию 30. Время ожидания ответа от номера, заданного в параметре contact,
                                                                если ответ не был получен, то вызов завершается. Время задаётся в секундах.
                                            example: 123
                                        direction:
                                            type: string
                                            description: "Значение по умолчанию in. \n                Определяет направление звонка in - Входящий звонок, out - Исходящий звонок."
                                            example: in
                                            enum:
                                                - in
                                                - out
                                        dtmf_string:
                                            type: string
                                            description: |-
                                                Задаёт DTMF, который будет отправлен абоненту, заданному в параметре contact. С
                                                                помощью символа . = '1 секунда' можно задать таймаут по истечению которого символ DTMF будет отправлен. Пример: .12.1..4, т.е через 1 секунду
                                                                будет отправлена цифра 12, далее через 1 секунду будет отправлена цифра 1 и через 2 секунды цифра 4.
                                            example: 0-9
                                            enum:
                                                - 0-9
                                                - '*'
                                                - '#'
                                        external_id:
                                            type: string
                                            description: Уникальный идентификатор, который может быть использован для связи события звонка с внешней системой.
                                            example: example_string
                                        virtual_phone_number:
                                            type: string
                                            description: |-
                                                Виртуальный номер, арендуемый клиентом. Формат номера должен соответствовать международному
                                                                    стандарту E.164 (например, 74993720692). Всегда используется в качестве номера звонящего при звонке
                                                                    на номер, указанный в параметре contact. Виртуальные номера можно получить с помощью REST
                                                                    API метода - Получение списка виртуальных номеров
                                            example: example_string
                                        virtual_phone_usage_rule:
                                            type: string
                                            description: "Правило использования виртуального номера. Позволяет динамически менять виртуальный номер при звонке. Если подходящий номер,\n                    удовлетворяющий выбранному правилу, не найден, то будет использован номер, указанный в параметре virtual_phone_number.\n                    Допустимые значения параметра:\n                \n                \n                    fixed - Фиксированный\n                    fixed_for_numa - Фиксированный для абонента\n                    random - Случайный\n                    regional_random - Региональный случайный\n                    regional_fixed_for_numa - Региональный фиксированный для абонента\n                \n                \n                    По умолчанию используется правило Фиксированный. Остальные правила доступны при подключённом компоненте\n                    Автоматическое управление номерами."
                                            example: example_string
                                    required:
                                        - access_token
                                        - virtual_phone_number
                                        - contact
                                        - contact_message
                            required:
                                - jsonrpc
                                - id
                                - method
                                - params
            responses:
                "200":
                    description: Successful response
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    id:
                                        type: number
                                        description: Request identifier
                                    jsonrpc:
                                        type: string
                                        description: JSON-RPC version
                                        example: "2.0"
                                    result:
                                        type: object
                                        properties:
                                            data:
                                                type: object
                                                properties:
                                                    call_session_id:
                                                        type: number
                                                        description: Уникальный идентификатор сессии звонка
                                                        example: 123
                                                required:
                                                    - call_session_id
                                            metadata:
                                                type: object
                                                description: Response metadata
                                        required:
                                            - data
                                            - metadata
                                required:
                                    - jsonrpc
                                    - id
                                    - result
                "400":
                    description: Error response
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    error:
                                        type: object
                                        properties:
                                            code:
                                                type: number
                                            data:
                                                type: object
                                            message:
                                                type: string
                                    id:
                                        type: number
                                    jsonrpc:
                                        type: string
            tags:
                - novofon
x-errors:
    errors:
        - code: "-32602"
          mnemonic: tts_text_exceeded
          description: Длина сообщения превысила допустимое ограничение, установленное тарифным планом
        - code: "-32602"
          mnemonic: media_file_not_found
          description: ""
        - code: "-32007"
          mnemonic: virtual_phone_number_not_found
          description: Если используется виртуальный номер не принадлежащий клиенту
        - code: "-32602"
          mnemonic: own_virtual_phone_number_not_allowed
          description: Звонок на собственный виртуальный номер запрещён
        - code: "-32602"
          mnemonic: contact_in_blacklist
          description: ""
        - code: "-32602"
          mnemonic: character_encoding_not_allowed
          description: ""
