openapi: 3.0.0
info:
    title: Send dtmf
    version: 1.0.0
    description: Отправка DTMF сотрудником. Метод Используется в случае, если на стороне клиента есть IVR и требуется выбрать в нём пункт меню.
paths:
    /send.dtmf:
        post:
            summary: Send dtmf
            description: |-
                Отправка DTMF сотрудником. Метод Используется в случае, если на стороне клиента есть IVR и требуется выбрать в нём пункт меню.

                **Request Parameters:** 3

                - `access_token` (string, required): Ключ сессии аутентификации

                - `call_session_id` (number, required): Уникальный идентификатор сессии звонка, который может быть получен в ответном сообщении при вызове методов start.informer_call, start.vnumber_call, start.scenario_call, start.employee_call, с помощью сервера уведомлений или DATA API.

                - `dtmf_string` (string, required): Задаёт DTMF, который будет отправлен абоненту, который задан в параметре contact. В случае исходящего вызова с виртуальной АТС в сторону вызываемого абонента. Отправка DTMF возможна только одиночными символами. Так же возможно вызвать настроенные опции разговора. Для исходящих звонков, опции разговора будут доступны спустя 30 секунд.
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                id:
                                    type: number
                                    description: Request identifier
                                jsonrpc:
                                    type: string
                                    description: JSON-RPC version
                                    example: "2.0"
                                method:
                                    type: string
                                    description: Method name
                                    example: send.dtmf
                                params:
                                    type: object
                                    properties:
                                        access_token:
                                            type: string
                                            description: Ключ сессии аутентификации
                                            example: example_string
                                        call_session_id:
                                            type: number
                                            description: Уникальный идентификатор сессии звонка, который может быть получен в ответном сообщении при вызове методов start.informer_call, start.vnumber_call, start.scenario_call, start.employee_call, с помощью сервера уведомлений или DATA API.
                                            example: 123
                                        dtmf_string:
                                            type: string
                                            description: Задаёт DTMF, который будет отправлен абоненту, который задан в параметре contact. В случае исходящего вызова с виртуальной АТС в сторону вызываемого абонента. Отправка DTMF возможна только одиночными символами. Так же возможно вызвать настроенные опции разговора. Для исходящих звонков, опции разговора будут доступны спустя 30 секунд.
                                            example: 0-9
                                            enum:
                                                - 0-9
                                                - '*'
                                                - '#'
                                    required:
                                        - access_token
                                        - call_session_id
                                        - dtmf_string
                            required:
                                - jsonrpc
                                - id
                                - method
                                - params
            responses:
                "200":
                    description: Successful response
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    id:
                                        type: number
                                        description: Request identifier
                                    jsonrpc:
                                        type: string
                                        description: JSON-RPC version
                                        example: "2.0"
                                    result:
                                        type: object
                                        properties:
                                            data:
                                                type: object
                                            metadata:
                                                type: object
                                                description: Response metadata
                                        required:
                                            - data
                                            - metadata
                                required:
                                    - jsonrpc
                                    - id
                                    - result
                "400":
                    description: Error response
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    error:
                                        type: object
                                        properties:
                                            code:
                                                type: number
                                            data:
                                                type: object
                                            message:
                                                type: string
                                    id:
                                        type: number
                                    jsonrpc:
                                        type: string
            tags:
                - novofon
