openapi: 3.0.0
info:
    title: List talk options
    version: 1.0.0
    description: Получение списка опций разговора настроенных в Личном кабинете виртуальной АТС
paths:
    /list.talk_options:
        post:
            summary: List talk options
            description: |-
                Получение списка опций разговора настроенных в Личном кабинете виртуальной АТС

                **Request Parameters:** 1

                - `access_token` (string, required): Ключ сессии аутентификации

                **Response Parameters:** 4

                - `button_value` (object): Некоторые опции могут содержать название тега, название сценария и т.д. Данный объект содержит дополнительную информацию об опции разговора

                - `button` (string): Клавиша, которая вызывает опцию разговора

                - `mnemonic` (string): Мнемоническое имя опции разговора Возможные значения: finish_conversation - Завершить разговор tag_call - Проставить тег record_talk - Диктофон (запись разговора) transfer_call - Трансфер run_scenario - Выполнить сценарий call_coach - Позвонить тренеру receive_fax - Принять факс save_numa - Сохранить АОН в группу

                - `name` (string): Название опции разговора
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                id:
                                    type: number
                                    description: Request identifier
                                jsonrpc:
                                    type: string
                                    description: JSON-RPC version
                                    example: "2.0"
                                method:
                                    type: string
                                    description: Method name
                                    example: list.talk_options
                                params:
                                    type: object
                                    properties:
                                        access_token:
                                            type: string
                                            description: Ключ сессии аутентификации
                                            example: example_string
                                    required:
                                        - access_token
                            required:
                                - jsonrpc
                                - id
                                - method
                                - params
            responses:
                "200":
                    description: Successful response
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    id:
                                        type: number
                                        description: Request identifier
                                    jsonrpc:
                                        type: string
                                        description: JSON-RPC version
                                        example: "2.0"
                                    result:
                                        type: object
                                        properties:
                                            data:
                                                type: object
                                                properties:
                                                    button:
                                                        type: string
                                                        description: Клавиша, которая вызывает опцию разговора
                                                        example: example_string
                                                    button_value:
                                                        type: object
                                                        description: Некоторые опции могут содержать название тега, название сценария и т.д. Данный объект содержит дополнительную информацию об опции разговора
                                                    mnemonic:
                                                        type: string
                                                        description: 'Мнемоническое имя опции разговора Возможные значения: finish_conversation - Завершить разговор tag_call - Проставить тег record_talk - Диктофон (запись разговора) transfer_call - Трансфер run_scenario - Выполнить сценарий call_coach - Позвонить тренеру receive_fax - Принять факс save_numa - Сохранить АОН в группу'
                                                        example: example_string
                                                    name:
                                                        type: string
                                                        description: Название опции разговора
                                                        example: example_string
                                                required:
                                                    - button
                                                    - mnemonic
                                                    - name
                                            metadata:
                                                type: object
                                                description: Response metadata
                                        required:
                                            - data
                                            - metadata
                                required:
                                    - jsonrpc
                                    - id
                                    - result
                "400":
                    description: Error response
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    error:
                                        type: object
                                        properties:
                                            code:
                                                type: number
                                            data:
                                                type: object
                                            message:
                                                type: string
                                    id:
                                        type: number
                                    jsonrpc:
                                        type: string
            tags:
                - novofon
